<?php

namespace Database\Seeders;

use App\Models\ResourceSource;
use Illuminate\Database\Seeder;

class ResourceSourcesSeeder extends Seeder
{
    public function run(): void
    {
        $sources = [
            [
                'key' => 'transferegov',
                'name' => 'Transferegov',
                'resource_scope' => 'federal',
                'capture_method' => 'api_official',
                'pipeline_group' => 'group_a_api',
                'refresh_frequency' => 'daily',
                'operational_status' => 'pipeline_next',
                'source_url' => 'https://api.transferegov.sistema.gov.br/api-docs',
                'access_guide' => 'Consultar convenios, propostas e programas federais com filtros por orgao, modalidade, município e periodo.',
                'index_fields' => ['orgao', 'programa', 'modalidade', 'uf', 'município', 'prazo', 'valor'],
                'operational_tags' => ['api', 'convenios', 'propostas', 'federal'],
                'source_metadata' => [
                    'coverage_scope' => 'convenios e propostas federais com recorte por ente',
                    'primary_entrypoint' => 'api-docs oficial',
                    'operational_priority' => 'alta',
                    'current_readiness' => 'mapeada para pipeline dedicado',
                ],
                'maintenance_notes' => 'Manter compatibilidade com chaves antigas e revisar mudancas de schema da API.',
                'is_active' => true,
                'requires_human_curation' => false,
                'supports_municipality_sync' => true,
                'sort_order' => 10,
            ],
            [
                'key' => 'portal_transparencia',
                'name' => 'Portal da Transparencia Federal',
                'resource_scope' => 'federal',
                'capture_method' => 'api_official',
                'pipeline_group' => 'group_a_api',
                'refresh_frequency' => 'daily',
                'operational_status' => 'live',
                'source_url' => 'https://api.portaldatransparencia.gov.br/swagger-ui/index.html',
                'access_guide' => 'Usar endpoints oficiais para transferencias, convenios, emendas e despesas com filtros por ente e orgao.',
                'index_fields' => ['orgao', 'acao', 'funcao', 'programa', 'favorecido', 'município', 'valor'],
                'operational_tags' => ['api', 'transferencias', 'convenios', 'producao'],
                'source_metadata' => [
                    'coverage_scope' => 'transferencias e convenios com aderência municipal',
                    'primary_entrypoint' => 'swagger oficial do portal',
                    'operational_priority' => 'critica',
                    'current_readiness' => 'pipeline ja em operacao',
                ],
                'maintenance_notes' => 'Fonte principal atual do radar; validar limites, autenticacao e padroes de paginacao.',
                'is_active' => true,
                'requires_human_curation' => false,
                'supports_municipality_sync' => true,
                'sort_order' => 20,
            ],
            [
                'key' => 'fnde',
                'name' => 'FNDE',
                'resource_scope' => 'federal',
                'capture_method' => 'scraping',
                'pipeline_group' => 'group_b_scraping',
                'refresh_frequency' => 'weekly',
                'operational_status' => 'mapped',
                'source_url' => 'https://www.gov.br/fnde/pt-br',
                'access_guide' => 'Monitorar programas, resolucoes, editais e repasses ligados a educacao basica e infraestrutura escolar.',
                'index_fields' => ['programa', 'linha', 'tema', 'publicacao', 'prazo', 'valor', 'contrapartida'],
                'operational_tags' => ['educacao', 'scraping', 'editais', 'infraestrutura'],
                'source_metadata' => [
                    'coverage_scope' => 'educacao basica, transporte escolar e infraestrutura',
                    'primary_entrypoint' => 'portal gov.br/fnde',
                    'operational_priority' => 'alta',
                    'current_readiness' => 'catalogada para pipeline do grupo B',
                    'scraping_entrypoints' => [
                        'https://www.gov.br/fnde/pt-br',
                        'https://www.gov.br/fnde/pt-br/acesso-a-informacao/acoes-e-programas',
                        'https://www.gov.br/fnde/pt-br/acesso-a-informacao/acoes-e-programas/programas',
                    ],
                    'scraping_path_keywords' => ['acoes-e-programas', 'programas', 'editais', 'resolucoes'],
                    'scraping_allowed_hosts' => ['www.gov.br', 'gov.br'],
                    'scraping_required_terms' => ['educacao', 'escola', 'escolar', 'creche', 'transporte escolar', 'onibus escolar', 'alimentacao escolar', 'quadra', 'programa', 'edital', 'resolucao'],
                    'scraping_title_terms' => ['educacao', 'escola', 'escolar', 'creche', 'transporte', 'onibus', 'alimentacao', 'quadra', 'programa', 'edital', 'resolucao', 'chamada', 'par', 'pnate', 'pnae', 'caminho da escola', 'brasil alfabetizado'],
                    'scraping_excluded_path_keywords' => ['noticias', 'agenda', 'acesso-a-informacao', 'comunicados', 'imprensa', 'auditorias', 'ouvidoria', 'servidor', 'licitacoes', 'legislacao'],
                    'require_strong_signal' => true,
                    'minimum_score' => 14,
                ],
                'maintenance_notes' => 'Observar mudancas de estrutura nas paginas do portal e documentos PDF anexos.',
                'is_active' => true,
                'requires_human_curation' => false,
                'supports_municipality_sync' => true,
                'sort_order' => 30,
            ],
            [
                'key' => 'funasa',
                'name' => 'Funasa',
                'resource_scope' => 'federal',
                'capture_method' => 'scraping',
                'pipeline_group' => 'group_b_scraping',
                'refresh_frequency' => 'weekly',
                'operational_status' => 'mapped',
                'source_url' => 'https://www.gov.br/funasa/pt-br',
                'access_guide' => 'Monitorar editais, chamadas e noticias tecnicas relacionadas a saneamento e saude ambiental.',
                'index_fields' => ['edital', 'tema', 'objeto', 'publicacao', 'prazo', 'uf', 'valor'],
                'operational_tags' => ['saneamento', 'saude', 'scraping', 'editais'],
                'source_metadata' => [
                    'coverage_scope' => 'saneamento, residuos e saude ambiental',
                    'primary_entrypoint' => 'portal gov.br/funasa',
                    'operational_priority' => 'alta',
                    'current_readiness' => 'catalogada para pipeline do grupo B',
                    'scraping_path_keywords' => ['editais', 'programas', 'saneamento', 'saude-ambiental', 'engenharia-de-saude-publica'],
                    'scraping_allowed_hosts' => ['www.gov.br', 'gov.br'],
                    'scraping_excluded_path_keywords' => ['noticias', 'agenda', 'acesso-a-informacao', 'imprensa', 'ouvidoria', 'servidor', 'licitacoes', 'concursos', 'galeria'],
                    'scraping_required_terms' => ['saneamento', 'agua', 'esgotamento', 'residuos', 'saude ambiental', 'engenharia de saude publica', 'obra', 'convenio', 'abastecimento'],
                    'scraping_title_terms' => ['saneamento', 'agua', 'esgotamento', 'residuos', 'ambiental', 'engenharia', 'obra', 'edital', 'chamada', 'programa'],
                    'require_strong_signal' => true,
                    'minimum_score' => 14,
                ],
                'maintenance_notes' => 'Priorizar paginas de editais e noticias; parte do conteudo pode migrar entre seções.',
                'is_active' => true,
                'requires_human_curation' => false,
                'supports_municipality_sync' => true,
                'sort_order' => 40,
            ],
            [
                'key' => 'fns',
                'name' => 'Fundo Nacional de Saude',
                'resource_scope' => 'federal',
                'capture_method' => 'scraping',
                'pipeline_group' => 'group_b_scraping',
                'refresh_frequency' => 'daily',
                'operational_status' => 'mapped',
                'source_url' => 'https://portalfns.saude.gov.br/',
                'access_guide' => 'Capturar incentivos, portarias, transferencias e programas com elegibilidade municipal na area da saude.',
                'index_fields' => ['programa', 'bloco', 'portaria', 'prazo', 'valor', 'criterio', 'habilitacao'],
                'operational_tags' => ['saude', 'portarias', 'incentivos', 'scraping'],
                'source_metadata' => [
                    'coverage_scope' => 'incentivos e transferencias acionaveis da saude',
                    'primary_entrypoint' => 'Portal FNS',
                    'operational_priority' => 'alta',
                    'current_readiness' => 'catalogada para pipeline do grupo B',
                    'scraping_entrypoints' => [
                        'https://portalfns.saude.gov.br/',
                        'https://portalfns.saude.gov.br/financiamento-da-saude/',
                        'https://portalfns.saude.gov.br/transferencias-fundo-a-fundo/',
                    ],
                    'scraping_path_keywords' => ['financiamento', 'transferencias', 'incentivo', 'portaria', 'bloco'],
                    'scraping_allowed_hosts' => ['portalfns.saude.gov.br'],
                    'scraping_required_terms' => ['saude', 'sus', 'portaria', 'incentivo', 'custeio', 'investimento', 'habilitacao', 'fundo a fundo', 'ubs', 'caps', 'atencao primaria'],
                    'scraping_title_terms' => ['saude', 'sus', 'portaria', 'incentivo', 'custeio', 'investimento', 'habilitacao', 'ubs', 'caps'],
                    'minimum_score' => 12,
                ],
                'maintenance_notes' => 'Conferir dependencias de consulta dinamica e distinguir transferencias automaticas de oportunidades acionaveis.',
                'is_active' => true,
                'requires_human_curation' => false,
                'supports_municipality_sync' => true,
                'sort_order' => 50,
            ],
            [
                'key' => 'fnas',
                'name' => 'FNAS',
                'resource_scope' => 'federal',
                'capture_method' => 'scraping',
                'pipeline_group' => 'group_b_scraping',
                'refresh_frequency' => 'weekly',
                'operational_status' => 'mapped',
                'source_url' => 'https://www.gov.br/mds/pt-br/acoes-e-programas/fnas',
                'access_guide' => 'Monitorar avisos, portarias e repasses do SUAS com foco em estrutura, servicos e cofinanciamento.',
                'index_fields' => ['acao', 'servico', 'publicacao', 'prazo', 'valor', 'criterio', 'equipamento'],
                'operational_tags' => ['assistencia-social', 'suas', 'scraping', 'cofinanciamento'],
                'source_metadata' => [
                    'coverage_scope' => 'servicos e estrutura da rede socioassistencial',
                    'primary_entrypoint' => 'portal MDS/FNAS',
                    'operational_priority' => 'media',
                    'current_readiness' => 'catalogada para pipeline do grupo B',
                    'scraping_path_keywords' => ['fnas', 'suas', 'cofinanciamento', 'portarias', 'protecao-social', 'assistencia-social'],
                    'scraping_allowed_hosts' => ['www.gov.br', 'gov.br'],
                    'scraping_excluded_path_keywords' => ['noticias', 'agenda', 'acesso-a-informacao', 'imprensa', 'ouvidoria', 'servidor', 'licitacoes', 'galeria', 'eventos'],
                    'scraping_required_terms' => ['assistencia social', 'suas', 'cofinanciamento', 'cras', 'creas', 'acolhimento', 'beneficio eventual', 'protecao social', 'servico'],
                    'scraping_title_terms' => ['fnas', 'suas', 'cofinanciamento', 'cras', 'creas', 'acolhimento', 'portaria', 'beneficio', 'servico'],
                    'require_strong_signal' => true,
                    'minimum_score' => 15,
                ],
                'maintenance_notes' => 'Relacionar conteudo com CRAS, CREAS e servicos socioassistenciais recorrentes.',
                'is_active' => true,
                'requires_human_curation' => false,
                'supports_municipality_sync' => true,
                'sort_order' => 60,
            ],
            [
                'key' => 'emendas_parlamentares',
                'name' => 'Emendas Parlamentares',
                'resource_scope' => 'federal',
                'capture_method' => 'api_official',
                'pipeline_group' => 'group_a_api',
                'refresh_frequency' => 'daily',
                'operational_status' => 'pipeline_next',
                'source_url' => 'https://api.portaldatransparencia.gov.br/swagger-ui/index.html',
                'access_guide' => 'Cruzar emendas, beneficiarios, autores e situacao de empenho com foco em repasses municipais.',
                'index_fields' => ['autor', 'numero_emenda', 'orgao', 'município', 'situacao', 'valor', 'ano'],
                'operational_tags' => ['api', 'emendas', 'autores', 'federal'],
                'source_metadata' => [
                    'coverage_scope' => 'emendas com filtros dedicados por autor e beneficiario',
                    'primary_entrypoint' => 'Portal da Transparencia',
                    'operational_priority' => 'alta',
                    'current_readiness' => 'catalogada como fonte especializada',
                ],
                'maintenance_notes' => 'Tratar como fonte especializada, mesmo usando dados da Transparencia, para permitir filtros dedicados.',
                'is_active' => true,
                'requires_human_curation' => false,
                'supports_municipality_sync' => true,
                'sort_order' => 70,
            ],
            [
                'key' => 'bndes',
                'name' => 'BNDES',
                'resource_scope' => 'financiamento',
                'capture_method' => 'scraping',
                'pipeline_group' => 'group_b_scraping',
                'refresh_frequency' => 'weekly',
                'operational_status' => 'mapped',
                'source_url' => 'https://www.bndes.gov.br/',
                'access_guide' => 'Monitorar linhas de credito, fundos, editais e programas de apoio a infraestrutura e desenvolvimento local.',
                'index_fields' => ['linha', 'tema', 'beneficiario', 'prazo', 'taxa', 'garantia', 'valor'],
                'operational_tags' => ['financiamento', 'credito', 'infraestrutura', 'scraping'],
                'source_metadata' => [
                    'coverage_scope' => 'linhas de credito e apoio a investimento publico',
                    'primary_entrypoint' => 'portal BNDES',
                    'operational_priority' => 'media',
                    'current_readiness' => 'catalogada para pipeline do grupo B',
                    'scraping_entrypoints' => [
                        'https://www.bndes.gov.br/wps/portal/site/home/financiamento',
                        'https://www.bndes.gov.br/wps/portal/site/home/financiamento/produto/',
                        'https://www.bndes.gov.br/wps/portal/site/home/financiamento/guia/',
                    ],
                    'scraping_path_keywords' => ['financiamento', 'produto', 'guia', 'setor-publico', 'infraestrutura'],
                    'scraping_allowed_hosts' => ['www.bndes.gov.br', 'bndes.gov.br'],
                    'minimum_score' => 10,
                ],
                'maintenance_notes' => 'Separar financiamento de subvencao e registrar requisitos de garantias ou contrapartida.',
                'is_active' => true,
                'requires_human_curation' => false,
                'supports_municipality_sync' => true,
                'sort_order' => 80,
            ],
            [
                'key' => 'caixa',
                'name' => 'Caixa Economica Federal',
                'resource_scope' => 'financiamento',
                'capture_method' => 'scraping',
                'pipeline_group' => 'group_b_scraping',
                'refresh_frequency' => 'weekly',
                'operational_status' => 'mapped',
                'source_url' => 'https://www.caixa.gov.br/',
                'access_guide' => 'Acompanhar programas de habitacao, saneamento, mobilidade e linhas operadas para entes publicos.',
                'index_fields' => ['programa', 'linha', 'tema', 'prazo', 'garantia', 'valor', 'contrapartida'],
                'operational_tags' => ['financiamento', 'habitacao', 'saneamento', 'scraping'],
                'source_metadata' => [
                    'coverage_scope' => 'habitacao, saneamento, mobilidade e operacoes com governo',
                    'primary_entrypoint' => 'portal Caixa',
                    'operational_priority' => 'media',
                    'current_readiness' => 'catalogada para pipeline do grupo B',
                    'scraping_entrypoints' => [
                        'https://www.caixa.gov.br/poder-publico/Paginas/default.aspx',
                        'https://www.caixa.gov.br/empresa/solucoes-financeiras/credito/Paginas/default.aspx',
                    ],
                    'scraping_path_keywords' => ['poder-publico', 'credito', 'saneamento', 'infraestrutura', 'mobilidade'],
                    'scraping_allowed_hosts' => ['www.caixa.gov.br', 'caixa.gov.br'],
                    'scraping_excluded_path_keywords' => ['loterias', 'voce', 'atendimento', 'beneficios-sociais', 'cartoes', 'seguranca', 'imprensa', 'ouvidoria', 'trabalhador', 'servidor', 'habitacao', 'minha-casa-minha-vida', 'contas', 'beneficios'],
                    'scraping_required_terms' => ['poder publico', 'financiamento', 'saneamento', 'mobilidade', 'infraestrutura', 'contrapartida', 'município', 'prefeitura', 'ente publico'],
                    'scraping_required_term_groups' => [
                        ['poder publico', 'setor publico', 'ente publico', 'prefeitura', 'município'],
                        ['financiamento', 'credito', 'saneamento', 'mobilidade', 'infraestrutura', 'contrapartida'],
                    ],
                    'scraping_title_terms' => ['poder publico', 'financiamento', 'saneamento', 'mobilidade', 'infraestrutura', 'credito', 'prefeitura', 'município', 'ente publico'],
                    'require_strong_signal' => true,
                    'minimum_score' => 17,
                ],
                'maintenance_notes' => 'Revisar seções de governo e pages de programas operados em parceria com ministerios.',
                'is_active' => true,
                'requires_human_curation' => false,
                'supports_municipality_sync' => true,
                'sort_order' => 90,
            ],
            [
                'key' => 'banco_brasil',
                'name' => 'Banco do Brasil',
                'resource_scope' => 'financiamento',
                'capture_method' => 'scraping',
                'pipeline_group' => 'group_b_scraping',
                'refresh_frequency' => 'weekly',
                'operational_status' => 'mapped',
                'source_url' => 'https://www.bb.com.br/',
                'access_guide' => 'Monitorar linhas para setor publico, modernizacao administrativa e investimento municipal.',
                'index_fields' => ['linha', 'segmento', 'prazo', 'taxa', 'garantia', 'valor', 'finalidade'],
                'operational_tags' => ['financiamento', 'modernizacao', 'credito', 'scraping'],
                'source_metadata' => [
                    'coverage_scope' => 'linhas para setor publico e modernizacao administrativa',
                    'primary_entrypoint' => 'portal Banco do Brasil',
                    'operational_priority' => 'media',
                    'current_readiness' => 'catalogada para pipeline do grupo B',
                ],
                'maintenance_notes' => 'Registrar condicoes comerciais separadas de editais ou chamadas pontuais.',
                'is_active' => true,
                'requires_human_curation' => false,
                'supports_municipality_sync' => true,
                'sort_order' => 100,
            ],
            [
                'key' => 'finep',
                'name' => 'FINEP',
                'resource_scope' => 'financiamento',
                'capture_method' => 'scraping',
                'pipeline_group' => 'group_b_scraping',
                'refresh_frequency' => 'weekly',
                'operational_status' => 'mapped',
                'source_url' => 'https://www.finep.gov.br/',
                'access_guide' => 'Capturar chamadas, editais e linhas de inovacao, cidades inteligentes e tecnologia aplicada ao setor publico.',
                'index_fields' => ['edital', 'linha', 'tema', 'publicacao', 'prazo', 'valor', 'publico_alvo'],
                'operational_tags' => ['inovacao', 'tecnologia', 'cidades-inteligentes', 'scraping'],
                'source_metadata' => [
                    'coverage_scope' => 'inovacao publica, tecnologia e cidades inteligentes',
                    'primary_entrypoint' => 'portal FINEP',
                    'operational_priority' => 'media',
                    'current_readiness' => 'catalogada para pipeline do grupo B',
                    'scraping_entrypoints' => [
                        'https://www.finep.gov.br/chamadas-publicas',
                        'https://www.finep.gov.br/apoio-e-financiamento-externa',
                        'https://www.finep.gov.br/inovacao-e-pesquisa',
                    ],
                    'scraping_path_keywords' => ['chamadas-publicas', 'apoio-e-financiamento', 'inovacao', 'subvencao', 'tecnologia', 'chamadas', 'editais'],
                    'scraping_allowed_hosts' => ['www.finep.gov.br', 'finep.gov.br'],
                    'scraping_excluded_path_keywords' => ['noticias', 'agenda', 'acesso-a-informacao', 'imprensa', 'ouvidoria', 'licitacoes', 'servidor', 'transparencia', 'galeria'],
                    'scraping_required_terms' => ['inovacao', 'edital', 'chamada', 'subvencao', 'tecnologia', 'pesquisa', 'financiamento'],
                    'scraping_title_terms' => ['finep', 'inovacao', 'edital', 'chamada', 'subvencao', 'tecnologia', 'pesquisa', 'cidades inteligentes'],
                    'require_strong_signal' => false,
                    'minimum_score' => 11,
                ],
                'maintenance_notes' => 'Acompanhar chamadas publicas e documentos anexos com regras de elegibilidade específicas.',
                'is_active' => true,
                'requires_human_curation' => false,
                'supports_municipality_sync' => true,
                'sort_order' => 110,
            ],
            [
                'key' => 'bid',
                'name' => 'BID',
                'resource_scope' => 'multilateral',
                'capture_method' => 'human_curation',
                'pipeline_group' => 'group_d_human_curation',
                'refresh_frequency' => 'weekly',
                'operational_status' => 'curation_only',
                'source_url' => 'https://www.iadb.org/',
                'access_guide' => 'Curadoria de programas, cooperacoes tecnicas e chamadas multilaterais com aderência municipal indireta.',
                'index_fields' => ['programa', 'pais', 'tema', 'janela', 'prazo', 'valor', 'elegibilidade'],
                'operational_tags' => ['multilateral', 'curadoria', 'cooperacao', 'internacional'],
                'source_metadata' => [
                    'coverage_scope' => 'cooperacao tecnica e janelas multilaterais',
                    'primary_entrypoint' => 'portal institucional BID',
                    'operational_priority' => 'seletiva',
                    'current_readiness' => 'depende de workflow editorial',
                ],
                'maintenance_notes' => 'Fonte de curadoria humana; registrar oportunidades com contexto e traducao operacional.',
                'is_active' => true,
                'requires_human_curation' => true,
                'supports_municipality_sync' => false,
                'sort_order' => 120,
            ],
            [
                'key' => 'banco_mundial',
                'name' => 'Banco Mundial',
                'resource_scope' => 'multilateral',
                'capture_method' => 'human_curation',
                'pipeline_group' => 'group_d_human_curation',
                'refresh_frequency' => 'weekly',
                'operational_status' => 'curation_only',
                'source_url' => 'https://www.worldbank.org/',
                'access_guide' => 'Curadoria de programas, fundos e chamadas com potencial de parceria para municípios e estados.',
                'index_fields' => ['programa', 'tema', 'regiao', 'janela', 'prazo', 'valor', 'criterio'],
                'operational_tags' => ['multilateral', 'curadoria', 'fundos', 'parcerias'],
                'source_metadata' => [
                    'coverage_scope' => 'programas e fundos com encaixe institucional indireto',
                    'primary_entrypoint' => 'portal institucional Banco Mundial',
                    'operational_priority' => 'seletiva',
                    'current_readiness' => 'depende de workflow editorial',
                ],
                'maintenance_notes' => 'Necessita leitura contextual e eventual intermediacao institucional para elegibilidade.',
                'is_active' => true,
                'requires_human_curation' => true,
                'supports_municipality_sync' => false,
                'sort_order' => 130,
            ],
            [
                'key' => 'ndb',
                'name' => 'NDB',
                'resource_scope' => 'multilateral',
                'capture_method' => 'human_curation',
                'pipeline_group' => 'group_d_human_curation',
                'refresh_frequency' => 'weekly',
                'operational_status' => 'curation_only',
                'source_url' => 'https://www.ndb.int/',
                'access_guide' => 'Curadoria de linhas e chamadas de infraestrutura, sustentabilidade e desenvolvimento urbano.',
                'index_fields' => ['linha', 'tema', 'pais', 'prazo', 'valor', 'instrumento', 'criterio'],
                'operational_tags' => ['multilateral', 'curadoria', 'infraestrutura', 'sustentabilidade'],
                'source_metadata' => [
                    'coverage_scope' => 'linhas multilaterais para infraestrutura e sustentabilidade',
                    'primary_entrypoint' => 'portal institucional NDB',
                    'operational_priority' => 'seletiva',
                    'current_readiness' => 'depende de workflow editorial',
                ],
                'maintenance_notes' => 'Exige curadoria humana e analise de encaixe institucional antes de publicar no radar.',
                'is_active' => true,
                'requires_human_curation' => true,
                'supports_municipality_sync' => false,
                'sort_order' => 140,
            ],
            [
                'key' => 'programas_estaduais',
                'name' => 'Programas Estaduais',
                'resource_scope' => 'estadual',
                'capture_method' => 'diary_monitor',
                'pipeline_group' => 'group_c_diary_monitor',
                'refresh_frequency' => 'daily',
                'operational_status' => 'pipeline_next',
                'source_url' => null,
                'access_guide' => 'Monitorar DOE, portais estaduais e paginas de secretarias para oportunidades regionais por UF, com pilotos iniciais da Bahia e de Sao Paulo.',
                'index_fields' => ['uf', 'orgao', 'programa', 'edital', 'publicacao', 'prazo', 'valor'],
                'operational_tags' => ['estadual', 'doe', 'monitoramento', 'regional'],
                'source_metadata' => [
                    'coverage_scope' => 'diarios estaduais e portais de secretarias por UF, com pilotos iniciais configurados para BA e SP',
                    'primary_entrypoint' => 'lista configuravel por estado',
                    'operational_priority' => 'alta',
                    'current_readiness' => 'pilotos BA e SP configurados para o grupo C',
                    'diary_entrypoints' => [],
                    'diary_path_keywords' => [],
                    'diary_allowed_hosts' => [],
                    'diary_required_terms' => ['edital', 'chamada', 'portaria', 'programa', 'secretaria', 'convenio', 'repasse'],
                    'diary_title_terms' => ['edital', 'chamada', 'programa', 'secretaria', 'governo do estado', 'convenio'],
                    'diary_ignore_terms' => ['nomeacao', 'exoneracao', 'aposentadoria', 'ferias', 'pessoal', 'servidor', 'diaria', 'passagem', 'designacao'],
                    'diary_minimum_score' => 9,
                    'diary_require_strong_signal' => true,
                    'diary_state_profiles' => [
                        'BA' => [
                            'label' => 'Bahia',
                            'entrypoints' => [
                                'https://do.ba.gov.br/',
                                'https://www.ba.gov.br/car/editais',
                            ],
                            'allowed_hosts' => ['do.ba.gov.br', 'www.ba.gov.br', 'ba.gov.br'],
                            'required_terms' => ['edital', 'chamada', 'chamamento publico', 'processo seletivo', 'credenciamento', 'convocacao', 'programa', 'convenio', 'repasse', 'fomento'],
                            'title_terms' => ['edital', 'chamada', 'chamamento', 'processo seletivo', 'credenciamento', 'programa', 'convocacao', 'fomento', 'bahia'],
                            'ignore_terms' => ['licitacao', 'pregao', 'concorrencia', 'registro de precos', 'tomada de precos', 'aviso de licitacao', 'modo de disputa'],
                            'minimum_score' => 11,
                            'require_strong_signal' => true,
                        ],
                        'SP' => [
                            'label' => 'Sao Paulo',
                            'entrypoints' => [
                                'https://www.saude.sp.gov.br/ses/perfil/cidadao/licitacoes-cgaobras/chamamento-publico',
                                'https://www.cultura.sp.gov.br/sec_cultura/Arquivo_de_Editais/Editais_Fomento_Cultsp/Fomento_Cultsp_2025/realizacao_de_projetos_culturais_em_municípios_de_ate_50_mil_habitantes/',
                            ],
                            'allowed_hosts' => ['www.saude.sp.gov.br', 'saude.sp.gov.br', 'www.cultura.sp.gov.br', 'cultura.sp.gov.br', 'storageproac.blob.core.windows.net'],
                            'required_terms' => ['edital', 'chamamento publico', 'credenciamento', 'convocacao', 'convenio', 'fomento', 'programa', 'consulta publica', 'proac', 'município'],
                            'title_terms' => ['edital', 'chamamento', 'credenciamento', 'convenio', 'fomento', 'programa', 'proac', 'cultura', 'sao paulo'],
                            'ignore_terms' => ['licitacao', 'pregao', 'concorrencia', 'registro de precos', 'tomada de precos', 'aviso de licitacao', 'extrato de contrato', 'concurso publico', 'despacho', 'portaria'],
                            'minimum_score' => 12,
                            'require_strong_signal' => true,
                        ],
                    ],
                ],
                'maintenance_notes' => 'Operar com lista configuravel por estado; pilotos iniciais da Bahia e de Sao Paulo via DOE e portais tematicos. Revisar próximas UFs apos validar o debug operacional.',
                'is_active' => true,
                'requires_human_curation' => false,
                'supports_municipality_sync' => true,
                'sort_order' => 150,
            ],
            [
                'key' => 'diario_oficial_uniao',
                'name' => 'Diario Oficial da Uniao',
                'resource_scope' => 'transversal',
                'capture_method' => 'diary_monitor',
                'pipeline_group' => 'group_c_diary_monitor',
                'refresh_frequency' => 'daily',
                'operational_status' => 'pipeline_next',
                'source_url' => 'https://www.in.gov.br/',
                'access_guide' => 'Monitorar publicacoes oficiais com NLP e filtros por tema, município, ministerio, edital e prazo.',
                'index_fields' => ['secao', 'orgao', 'tema', 'publicacao', 'prazo', 'município', 'valor'],
                'operational_tags' => ['dou', 'nlp', 'monitoramento', 'publicacoes'],
                'source_metadata' => [
                    'coverage_scope' => 'publicacoes oficiais federais com filtro por relevancia',
                    'primary_entrypoint' => 'portal in.gov.br',
                    'operational_priority' => 'critica',
                    'current_readiness' => 'aguarda pipeline do grupo C',
                    'diary_entrypoints' => [
                        'https://www.in.gov.br/consulta/-/buscar/dou?q=edital',
                        'https://www.in.gov.br/consulta/-/buscar/dou?q=chamada',
                        'https://www.in.gov.br/consulta/-/buscar/dou?q=convenio',
                    ],
                    'diary_path_keywords' => ['buscar', 'dou'],
                    'diary_allowed_hosts' => ['www.in.gov.br', 'in.gov.br'],
                    'diary_required_terms' => ['edital', 'chamada', 'credenciamento', 'selecao', 'consulta publica', 'convenio', 'repasse', 'fomento', 'transferencia'],
                    'diary_required_term_groups' => [
                        ['edital', 'chamada', 'credenciamento', 'selecao', 'consulta publica', 'convenio'],
                        ['repasse', 'transferencia', 'fomento', 'proposta'],
                    ],
                    'diary_title_terms' => ['edital', 'chamada', 'credenciamento', 'convenio', 'repasse', 'fomento', 'selecao', 'consulta publica', 'transferencia'],
                    'diary_ignore_terms' => ['nomeacao', 'exoneracao', 'aposentadoria', 'ferias', 'pessoal', 'servidor', 'homologacao de concurso', 'designacao', 'substituicao', 'extrato', 'resultado de julgamento', 'homologacao', 'adjudicacao', 'pregao', 'concorrencia', 'dispensa de licitacao', 'inexigibilidade', 'retificacao'],
                    'diary_minimum_score' => 12,
                    'diary_require_strong_signal' => true,
                ],
                'maintenance_notes' => 'Necessita classificacao por relevancia para reduzir ruido e duplicidade com outras fontes.',
                'is_active' => true,
                'requires_human_curation' => false,
                'supports_municipality_sync' => true,
                'sort_order' => 160,
            ],
        ];

        foreach ($sources as $source) {
            ResourceSource::query()->updateOrCreate(
                ['key' => $source['key']],
                $source
            );
        }

        $this->command?->info('✅ Catalogo inicial de fontes do Radar de Recursos carregado.');
    }
}
